/**
 * MCP Server generator
 */

import type { GeneratorPlugin, GeneratorResult } from '../types';
import type { CommandRegistry } from '../../CommandRegistry';

export interface MCPServerOptions {
  outputPath: string;
  serverName?: string;
  serverVersion?: string;
  typescript?: boolean;
  dryRun?: boolean;
}

export class MCPServerGenerator implements GeneratorPlugin<MCPServerOptions, GeneratorResult> {
  readonly name = 'mcp-server';
  readonly description = 'Generate standalone MCP server';
  readonly outputExtensions = ['.ts', '.js'];

  async generate(
    registry: CommandRegistry,
    options: MCPServerOptions
  ): Promise<GeneratorResult> {
    const content = this.generateServerContent(registry, options);

    if (!options.dryRun) {
      const fs = require('fs-extra');
      const path = require('path');
      await fs.ensureDir(path.dirname(options.outputPath));
      await fs.writeFile(options.outputPath, content, 'utf-8');
    }

    return {
      files: [{
        path: options.outputPath,
        content,
        created: !options.dryRun
      }]
    };
  }

  private generateServerContent(registry: CommandRegistry, options: MCPServerOptions): string {
    const commands = registry.getAll();
    const serverName = options.serverName || 'universal-mcp-server';
    const serverVersion = options.serverVersion || '1.0.0';
    const ts = options.typescript !== false;

    // Serialize schemas without functions
    const commandSchemas = commands.map(cmd => this.serializeSchema(cmd.schema));

    return `/**
 * Auto-generated MCP Server
 * Name: ${serverName} v${serverVersion}
 * Tools: ${commands.length}
 *
 * Generated by: @supernal/universal-command (mcp-server plugin)
 * DO NOT EDIT MANUALLY
 */

${ts ? "import { Server } from '@modelcontextprotocol/sdk/server';" : "const { Server } = require('@modelcontextprotocol/sdk/server');"}
${ts ? "import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio';" : "const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio');"}
import { createMCPServer } from '@supernal/universal-command/mcp';
import { CommandRegistry, UniversalCommand } from '@supernal/universal-command';

const registry = new CommandRegistry();

${commandSchemas.map(schema => `registry.register(new UniversalCommand(${JSON.stringify(schema, null, 2)}));`).join('\n\n')}

const server = createMCPServer(registry, {
  name: '${serverName}',
  version: '${serverVersion}'
});

const transport = new StdioServerTransport();
server.connect(transport);

console.error('MCP Server: ${serverName} v${serverVersion}');
console.error('Available tools: ${commands.length}');
`;
  }

  /**
   * Serialize schema for code generation, omitting functions
   */
  private serializeSchema(schema: any): any {
    const result: any = {};

    for (const [key, value] of Object.entries(schema)) {
      if (typeof value === 'function') {
        continue;
      } else if (value && typeof value === 'object' && !Array.isArray(value)) {
        result[key] = this.serializeSchema(value);
      } else {
        result[key] = value;
      }
    }

    return result;
  }
}
